const ActionTypes = {
    CHANGE_MAIN_TAB: 'CHANGE_MAIN_TAB',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_OUT: 'LOGIN_OUT',
}

module.exports = ActionTypes