const ActionTypes = {
    CHANGE_MAIN_TAB: 'CHANGE_MAIN_TAB',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_OUT: 'LOGIN_OUT',

    UNREADE_COUNT_UPDATE: 'UNREADE_COUNT_UPDATE',
    UNREADE_COUNT_CLEAR: 'UNREADE_COUNT_CLEAR',
    UNREAD_COUNT_START_FETCH: 'UNREAD_COUNT_START_FETCH',

    FRIENDLIST_UPDATE:'FRIENDLIST_UPDATE',
}

module.exports = ActionTypes