const ActionTypes = {
    TOKEN_SAVE: 'TOKEN_SAVE',
    TOKEN_REMOVE: 'TOKEN_REMOVE',
    TOKEN_FETCH: 'TOKEN_FETCH',
    TOKEN_FETCH_FAILURE: 'TOKEN_FETCH_FAILURE',

    CHANGE_MAIN_TAB: 'CHANGE_MAIN_TAB',
}

module.exports = ActionTypes